sudo: required 
language: generic 
services:
  - docker

before_install:
  - docker build -t asykhimky:docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true asykhimky:docker-react npm run test